twig:
    default_path: '%kernel.project_dir%/templates'
    globals: 
        copyright: 'Copyright © 2021 -  Amandine Bensekhri'
        contact_address: '1 rue des développeurs'
        contact_zip: 12345
        contact_city: 'DevLand'
        contact_phone: '01.23.45.67.89'
        contact_email: 'amandine.bensekhri@test.com'
